jQuery('#wowslider-container1').wowSlider({
	effect:"cube_over", 
	prev:"", 
	next:"", 
	duration: 20*100, 
	delay:20*100, 
	width:960,
	height:500,
	autoPlay:true,
	autoPlayVideo:false,
	playPause:false,
	stopOnHover:false,
	loop:false,
	bullets:1,
	caption: true, 
	captionEffect:"parallax",
	controls:true,
	responsive:1,
	fullScreen:false,
	gestures: 2,
	onBeforeStep:0,
	images:0,
	staticColor: true
});